/**
 * markerImages
 *
 * Pre-loaded PNG marker assets for react-native-maps `image` prop.
 * Generated by scripts/generate-marker-assets.js at @1x/@2x/@3x.
 * Metro automatically selects the right density variant.
 */
export const markerImages = {
  car: require('../../../assets/markers/marker-car.png'),
  carAssigned: require('../../../assets/markers/marker-car-assigned.png'),
  pickup: require('../../../assets/markers/marker-pickup.png'),
  dropoff: require('../../../assets/markers/marker-dropoff.png'),
  stopSmall: [
    null, // index 0 unused
    require('../../../assets/markers/marker-stop-small-1.png'),
    require('../../../assets/markers/marker-stop-small-2.png'),
    require('../../../assets/markers/marker-stop-small-3.png'),
    require('../../../assets/markers/marker-stop-small-4.png'),
    require('../../../assets/markers/marker-stop-small-5.png'),
    require('../../../assets/markers/marker-stop-small-6.png'),
    require('../../../assets/markers/marker-stop-small-7.png'),
    require('../../../assets/markers/marker-stop-small-8.png'),
    require('../../../assets/markers/marker-stop-small-9.png'),
  ],
};
