/**
 * markerImages
 *
 * Pre-loaded PNG marker assets registered with the Mapbox SDK at the top of
 * every map. The wrapper `MapViewWrapper` mounts a single `<Mapbox.Images>`
 * with this registry so any `<MarkerWrapper image={markerImages.X} />` resolves
 * the icon by reference. Keys here also become valid string identifiers for
 * `iconImage` style expressions (the wrapper translates require()-modules to
 * stable string IDs).
 *
 * Generated by scripts/generate-marker-assets.js at @1x/@2x/@3x.
 * Metro automatically selects the right density variant per device.
 */
export const markerImages = {
  carAssigned: require('../../../assets/markers/marker-car-assigned.png'),
  car: require('../../../assets/markers/marker-car.png'),
  destination: require('../../../assets/markers/marker-destination.png'),
  pickup: require('../../../assets/markers/marker-pickup.png'),
  dropoff: require('../../../assets/markers/marker-dropoff.png'),
  user: require('../../../assets/markers/marker-user.png'),
  // Cluster + BoltPin backgrounds — overlaid by SymbolLayer textField via iconTextFit.
  clusterBg: require('../../../assets/markers/marker-cluster-bg.png'),
  boltpinBgDark: require('../../../assets/markers/marker-boltpin-bg-dark.png'),
  boltpinBgGreen: require('../../../assets/markers/marker-boltpin-bg-green.png'),
  stop: [
    null, // index 0 unused
    require('../../../assets/markers/marker-stop-1.png'),
    require('../../../assets/markers/marker-stop-2.png'),
    require('../../../assets/markers/marker-stop-3.png'),
    require('../../../assets/markers/marker-stop-4.png'),
    require('../../../assets/markers/marker-stop-5.png'),
    require('../../../assets/markers/marker-stop-6.png'),
    require('../../../assets/markers/marker-stop-7.png'),
    require('../../../assets/markers/marker-stop-8.png'),
    require('../../../assets/markers/marker-stop-9.png'),
  ],
  stopSmall: [
    null,
    require('../../../assets/markers/marker-stop-small-1.png'),
    require('../../../assets/markers/marker-stop-small-2.png'),
    require('../../../assets/markers/marker-stop-small-3.png'),
    require('../../../assets/markers/marker-stop-small-4.png'),
    require('../../../assets/markers/marker-stop-small-5.png'),
    require('../../../assets/markers/marker-stop-small-6.png'),
    require('../../../assets/markers/marker-stop-small-7.png'),
    require('../../../assets/markers/marker-stop-small-8.png'),
    require('../../../assets/markers/marker-stop-small-9.png'),
  ],
};

/**
 * Reverse lookup: require()-module identity → string ID for Mapbox SymbolLayer.
 * SymbolLayer's `iconImage` expects a string that matches a key registered
 * via `<Mapbox.Images images={...}>`. Because every consumer passes the
 * markerImages.X reference (not a string), the wrapper does this lookup.
 *
 * IDs are prefixed with `lulini_` so they don't collide with images already
 * baked into the active Mapbox style (e.g. `streets-v12` ships its own `car`
 * icon — without the namespace prefix, Mapbox warns and the style image wins).
 *
 * Synthesised lazily so adding a key to `markerImages` above is enough.
 */
const ID_PREFIX = 'lulini_';

let _idLookup = null;
function buildLookup() {
  const map = new Map();
  for (const [key, value] of Object.entries(markerImages)) {
    if (Array.isArray(value)) {
      for (let i = 0; i < value.length; i++) {
        if (value[i]) map.set(value[i], `${ID_PREFIX}${key}_${i}`);
      }
    } else if (value) {
      map.set(value, `${ID_PREFIX}${key}`);
    }
  }
  return map;
}

export function imageIdFor(imageRef) {
  if (typeof imageRef === 'string') return imageRef;
  if (!imageRef) return null;
  if (!_idLookup) _idLookup = buildLookup();
  return _idLookup.get(imageRef) ?? null;
}

/**
 * Flat object keyed by string ID — `<Mapbox.Images images={mapboxImageMap}>` consumes this.
 */
export function buildMapboxImageMap() {
  const out = {};
  for (const [key, value] of Object.entries(markerImages)) {
    if (Array.isArray(value)) {
      for (let i = 0; i < value.length; i++) {
        if (value[i]) out[`${ID_PREFIX}${key}_${i}`] = value[i];
      }
    } else if (value) {
      out[`${ID_PREFIX}${key}`] = value;
    }
  }
  return out;
}
